#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Enable bash script
shopt -s extglob

# Delete all files for processor
rm -rf *[0-9].*[0-9] processor* log.*


#------------------------------------------------------------------------------
