#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Enable bash script
shopt -s extglob

# Git routine
git add .

echo ">>> Commit:"
read -r Comment

git commit -m "$Comment"

git push origin master

#------------------------------------------------------------------------------
